### ISSUE TITLE
请教一下winform程序怎么使用服务级模型

### ISSUE THREAD

**Issue by huaxuanHan** [raoyutian/PaddleOCRSharp#1]
在gunet上面引用了PaddleOCRSharp，直接就能使用了，很方便，但是想要结果更准确，想使用服务级模型，需要怎么做啊，麻烦大佬指导一下

**Comment by raoyutian** [comment]
nuget不是最新的，github也不是最新的。
去码云下载最新版项目：https://gitee.com/raoyutian/paddle-ocrsharp
模型下载地址：https://gitee.com/paddlepaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md
关注QQ群：318860399，可以获取最新版本以及新功能
