### ISSUE TITLE
请问如何启用GPU

### ISSUE THREAD

**Issue by s084088** [raoyutian/PaddleOCRSharp#11]
我希望使用GPU进行预测,
但每次都会遇到Please compile with gpu to EnableGpu()这个问题
请问如何操作,

**Comment by raoyutian** [comment]
GPU进行预测，不仅需要更改参数，还需要硬件适配，还需要另外的GPU专用的预测库。
本项目没有提供专用的GPU预测库。QQ群提供一个版本的GPU预测库。

**Comment by s084088** [comment]
好的,感谢
