### ISSUE TITLE
运行 PaddleOCRSharpDemo出错

### ISSUE THREAD

**Issue by tiger2014** [raoyutian/PaddleOCRSharp#12]
提示找不到

*\PaddleOCRSharp\PaddleOCRDemo\PaddleOCRSharpDemo\bin\Debug\inferenceserver\ch_ppocr_server_v2.0_det_infer
*\PaddleOCRSharp\PaddleOCRDemo\PaddleOCRSharpDemo\bin\Debug\inferenceserver\ch_ppocr_mobile_v2.0_cls_infer
*\PaddleOCRSharp\PaddleOCRDemo\PaddleOCRSharpDemo\bin\Debug\inferenceserver\ch_ppocr_server_v2.0_rec_infer
*\PaddleOCRSharp\PaddleOCRDemo\PaddleOCRSharpDemo\bin\Debug\inferenceserver\ppocr_keys.txt

这些东西项目里面都没有，项目不能运行，你的说明文档里面也没有这部分内容。麻烦更新一下文档

**Comment by raoyutian** [comment]
项目中默认带一个简体中文版模型
