### ISSUE TITLE
希望可以支持linux下运行

### ISSUE THREAD

**Issue by haifding** [raoyutian/PaddleOCRSharp#13]
centos7.9

**Comment by haifding** [comment]
很多.net core3.1 /  .net5  / .net6  都要放到linux服务器上去运行得，不然这个跨平台是无法使用得。希望作者考虑一下，谢谢

**Comment by raoyutian** [comment]
主要难点是PaddleOCR.dll的跨平台问题。C++编译跨平台目前还有很多问题要处理

**Comment by Vict0r-Chen** [comment]
@raoyutian 请教大佬，PaddleOCR.dll不是按照[这个教程](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/readme_ch.md#22)然后更改cmake配置来编译生成的吗？不是本应该就可以在linux上跑了吗？

**Comment by raoyutian** [comment]
> @raoyutian 请教大佬，PaddleOCR.dll不是按照[这个教程](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/readme_ch.md#22)然后更改cmake配置来编译生成的吗？不是本应该就可以在linux上跑了吗？
能编译，不能直接使用，缺少依赖。比较麻烦。官方有docker。
