### ISSUE TITLE
内存占用问题

### ISSUE THREAD

**Issue by raozhihao** [raoyutian/PaddleOCRSharp#17]
在使用的时候我发现识别一张图的时候
其内存会暴涨到600多兆
而且后面也无法释放
不知道是否属于正常情况

**Comment by raoyutian** [comment]
底层数学加速库的问题，我也无法解决。

**Comment by n0099** [comment]
https://github.com/sdcb/PaddleSharp/pull/46

**Comment by raoyutian** [comment]
> [sdcb/PaddleSharp#46](https://github.com/sdcb/PaddleSharp/pull/46)

该问题属于底层MKL加速库问题，你所说的方法，并不能根本上解决。该方法已经在PaddleOCRSharp项目中使用了。
但内存仍会增加。
同样的模型，不用Paddle的推理库，换成openvino的库，内存根本不涨也就300M左右，CPU也不高。
