### ISSUE TITLE
Nuget包怎么去掉命令行打印

### ISSUE THREAD

**Issue by madaOmada** [raoyutian/PaddleOCRSharp#19]
控制台应用程序 PaddleOCREngine实例化时会出现如下打印输出，怎么去掉？
![image](https://user-images.githubusercontent.com/34056346/195542768-e214a673-1e01-4410-9caa-f8272db44274.png)

**Comment by raoyutian** [comment]
下一版。

**Comment by raoyutian** [comment]
2.1.0版本已经禁用了日志。
