### ISSUE TITLE
为什么我使用3080显卡比用cpu慢三倍左右

### ISSUE THREAD

**Issue by Novazrl** [raoyutian/PaddleOCRSharp#21]
为什么我使用3080显卡比用cpu慢三倍左右

**Comment by raoyutian** [comment]
需要编译GPU版本的dll，以及开启GPU，各种环境CUDA,CUDNN,TR都要匹配。QQ群：318860399了解更多

**Comment by raoyutian** [comment]
使用GPU版本但GPU环境不正确，可能自动以CPU模式运行，就会比纯CPU版本的慢。
