### ISSUE TITLE
Not Detect the Space

### ISSUE THREAD

**Issue by kmuthugtk** [raoyutian/PaddleOCRSharp#22]
Hi,

I have a image with space in between the character. But it's ignore, kindly help me to fix this issue.

Thank you

**Comment by raoyutian** [comment]
Hi
You can try resize the image   and try again.


If your image width or height s greater than 2000，
In C# Code
`//The v3.0.0 is max_side_len
OCRParameter.max_side_len = 2000;
//if you use  a  other version,
OCRParameter.MaxSideLen= 2000;
`
In  C++  code   is   "max_side_len".

and try again.

thank you

**Comment by kmuthugtk** [comment]
Hi,

I tried, but still it's same. Here I attached the Image for your reference. 
![ocr_1_original](https://user-images.githubusercontent.com/76728951/232657101-58f2b5ce-7531-4674-8c7d-f66e4be5b39f.jpg)

Expected output:
99702000
292.0087
817618.000
2534
4B10P

If have the space in between the two character, split as separate line

Kindly help me to solve this

Thank you

**Comment by raoyutian** [comment]
You can try use the  en_V3 model.

  [en_V3 model](https://gitee.com/raoyutian/paddle-ocrsharp/tree/dev/models/PP-OCRv3)

![1681787951381](https://user-images.githubusercontent.com/72854228/232662299-374cc316-3eba-49e1-9fad-848a479048d2.png)


Example of using c #
         ```
         OCRModelConfig config = new OCRModelConfig();
            string root = System.IO.Path.GetDirectoryName(typeof(OCRModelConfig).Assembly.Location);
            string modelPathroot = root + @"\en_v3";
            config.det_infer = modelPathroot + @"\en_PP-OCRv3_det_infer";
            config.cls_infer = modelPathroot + @"\ch_ppocr_mobile_v2.0_cls_infer";
            config.rec_infer = modelPathroot + @"\en_PP-OCRv3_rec_infer";
            config.keys = modelPathroot + @"\en_dict.txt";

```

**Comment by kmuthugtk** [comment]
Hi,

I cannot find any folder like @"\en_v3" and @"\en_dict.txt"

![image](https://user-images.githubusercontent.com/76728951/232666686-465f9aa7-7e88-48e1-a27c-bc08455930be.png)

**Comment by raoyutian** [comment]
download url: 
https://gitee.com/raoyutian/paddle-ocrsharp/tree/dev/models/PP-OCRv3
and download  the  en_v3.zip

**Comment by kmuthugtk** [comment]
Thank you. It's helpful for me.


And If I have the flipped image, is it possible to get the correct OCR text.

![ocr_1_original](https://user-images.githubusercontent.com/76728951/232738659-54cd52b9-5d64-4569-a173-8953f407b954.jpg)

**Comment by raoyutian** [comment]
你好，项目默认没有开启方向识别参数，对于可能存在旋转的图像或者有旋转角度的文字，你可以设置如下参数
```
OCRParameter.cls= true;
OCRParameter.use_angle_cls= true;
```

![1681815970032(1)](https://user-images.githubusercontent.com/72854228/232758712-d51ecc56-7b76-429c-8e3a-4a864885a688.png)

下面链接，有详细参数的使用说明
https://gitee.com/raoyutian/paddle-ocrsharp/blob/master/doc/UseInCsharp.md

**Comment by kmuthugtk** [comment]
Hi,

I cannot able use this ASP.NET Core WebAPI, can't initialise the en_v3 directory. It gives the error as Value can't null in Production environments. 

Kindly please help me to solve this issues.

Thank you
