### ISSUE TITLE
Unable to find an entry point named 'Initialize' in DLL 'PaddleOCR.dll

### ISSUE THREAD

**Issue by jinleil** [raoyutian/PaddleOCRSharp#23]
无法创建引擎对象。环境信息是 Win10 + .NET6 + PaddleOCRSharp3.0.0

![image](https://user-images.githubusercontent.com/44106819/233581076-655dbb0e-d51f-4555-a572-171deda4966a.png)

**Comment by okaxuan** [comment]
> 无法创建引擎对象。环境信息是 Win10 + .NET6 + PaddleOCRSharp3.0.0
> 
> ![image](https://user-images.githubusercontent.com/44106819/233581076-655dbb0e-d51f-4555-a572-171deda4966a.png)

运行环境AnyCPU 改成X64

**Comment by raoyutian** [comment]
加QQ群318860399讨论
