### ISSUE TITLE
Training Set For This  Model

### ISSUE THREAD

**Issue by leviethung2103** [raoyutian/PaddleOCRSharp#27]
Hello, 

I am very interesting about the project. In comparsion with the orignal PaddleOCR, I've seen that the performance of your model is so good when detecting the small obejcts. 

Could you please share with me what you've changed in the model architecture and the training dataset you've used to train the model?

I am juts curious aabout the techniques. Thank you in advance.

**Comment by raoyutian** [comment]
请用中文描述，谢谢

**Comment by leviethung2103** [comment]
你好，

我对这个项目非常感兴趣。与原始的PaddleOCR相比，我注意到你的模型在检测小物体时性能非常好。

请问你能和我分享一下在模型架构方面和训练数据集方面做了哪些改进来训练这个模型吗？

我对其中的技术很好奇。非常感谢你提前的回答。

**Comment by raoyutian** [comment]
网络不好github经常无法打开。
我可以问下您是来自哪个国家吗？
你使用的是哪个模型？
