### ISSUE TITLE
likely... linux deployment environment is not supported ?

### ISSUE THREAD

**Issue by No54** [raoyutian/PaddleOCRSharp#29]
yt_CPUCheck.dll were not found...

is there something wrong about the configuration ? 

Thanks！

**Comment by raoyutian** [comment]
Currently, Linux deployment environments are not supported.

Support may be provided in the future

**Comment by n0099** [comment]
Try out https://github.com/sdcb/PaddleSharp

**Comment by No54** [comment]
OK，thanks T_T
