### ISSUE TITLE
Hi 我更换了 inference这个文件夹下的预测模型和参数使用别的模型和参数文件但是不能预测了。请问我要使用自己训练过的模型该怎么做。谢谢

### ISSUE THREAD

**Issue by kylecj77** [raoyutian/PaddleOCRSharp#3]
Hi 我更换了 inference这个文件夹下的预测模型和参数使用别的模型和参数文件但是不能预测了。请问我要使用自己训练过的模型该怎么做。谢谢

**Comment by raoyutian** [comment]
参考：
    //英文和数字模型
            OCRModelConfig config = new OCRModelConfig();
            string root = Environment.CurrentDirectory;
            string modelPathroot = root + @"\en";
            config.det_infer = modelPathroot + @"\ch_PP-OCRv2_det_infer";
            config.cls_infer = modelPathroot + @"\ch_ppocr_mobile_v2.0_cls_infer";
            config.rec_infer = modelPathroot + @"\en_number_mobile_v2.0_rec_infer";
            config.keys = modelPathroot + @"\en_dict.txt";
