### ISSUE TITLE
Could not load file or assembly 'MFCMIFC80, Version=1.0.0.0

### ISSUE THREAD

**Issue by ym9288** [raoyutian/PaddleOCRSharp#37]
![image](https://github.com/raoyutian/PaddleOCRSharp/assets/33686173/63841d04-e4f7-4b3a-ad60-2bd672c94f26)
我使用了Prism框架的插件模块，将OCR模块引入到我的插件项目（x64位编译）中,但是在APp启动加载插件时始终报这个错误，无法启动， 但是我单独搞一个Demo直接测试识别又是可以正常运行的

**Comment by raoyutian** [comment]
这可能是你的框架的依赖文件，MFC，是微软的C++的一个框架，我的类库与界面无关，用不到该依赖。

**Comment by raoyutian** [comment]
这可能是你的框架的依赖文件，MFC，是微软的C++的一个框架，我的类库与界面无关，用不到该依赖。
