### ISSUE TITLE
同样环境cpu版本测试发现paddleocrv4比v3版本要慢很多这是为啥

### ISSUE THREAD

**Issue by futureflsl** [raoyutian/PaddleOCRSharp#38]
我发现paddleocrv3在cpu速度大约500ms但是换成v4就是1秒左右

**Comment by raoyutian** [comment]
官方的V4本来就比V3慢。但官方宣称快一点。

**Comment by n0099** [comment]
AVX512 https://github.com/sdcb/PaddleSharp/issues/75
