### ISSUE TITLE
有没有办法优化下大小？

### ISSUE THREAD

**Issue by nianzx** [raoyutian/PaddleOCRSharp#39]
你好，我这边只是用了nuget引入相关依赖，生成的release就有300M，有没有什么办法可以优化下大小？

**Comment by raoyutian** [comment]
opencv依赖：opencv_world470.dll 62M
数据库依赖：mklml.dll 90M
CPU加速库依赖：mkldnn.dll 27M
飞桨框架：paddle_inference.dll 87M
这几个，哪个可以不要？已经266M了。

**Comment by q568741819** [comment]
单独做成一个服务，不要再业务项目中直接引用
