### ISSUE TITLE
循环调用DetectText报错

### ISSUE THREAD

**Issue by igaobingbing** [raoyutian/PaddleOCRSharp#41]
1、包版本
```c#
<PackageReference Include="PaddleOCRSharp" Version="4.2.0" />
```
2、PaddleOCREngine全局初始化
3、调用代码
```c#
 foreach (var file in Request.Form.Files)
 {
     var bytes = new byte[file.Length];
     using (var fileStream = file.OpenReadStream())
     {
         fileStream.Read(bytes, 0, (int)file.Length);
     }
     var text = ocr.DetectText(bytes);
     result.Add(new { key = file.FileName, value = text });
 }

```
```js
错误：
1、JsonSerializationException: Error converting value {null} to type 'System.Single'. Path '[0].cls_score', line 1, position 131.
2、InvalidCastException: Null object cannot be converted to a value type.
```

**Comment by raoyutian** [comment]
下个版本修复。
可能是升级Json序列化库导致。之前的版本一直没有这个问题。

**Comment by igaobingbing** [comment]
好吧，哪个版本没有问题呢
---- 回复的原邮件 ----
发件人Yutian ***@***.***>发送日期2024年04月20日 16:21 ***@***.***> ***@***.***>,
***@***.***>主题Re: [raoyutian/PaddleOCRSharp] 循环调用DetectText报错 (Issue #41)
下个版本修复。
可能是升级Json序列化库导致。之前的版本一直没有这个问题。

**Comment by raoyutian** [comment]
> 好吧，哪个版本没有问题呢 ---- 回复的原邮件 ---- 发件人Yutian ***@***.***>发送日期2024年04月20日 16:21 ***@***.***> ***@***.***>, ***@***.***>主题Re: [raoyutian/PaddleOCRSharp] 循环调用DetectText报错 (Issue #41) 下个版本修复。 可能是升级Json序列化库导致。之前的版本一直没有这个问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你可以试试4.1版本

**Comment by igaobingbing** [comment]
4.1版本也是如此

**Comment by raoyutian** [comment]
> 4.1版本也是如此

那就不你知道你的问题所在了，我自己以及别人的服务都好好的。

**Comment by igaobingbing** [comment]
我部署为 win 服务，然后多个客户端调用接口（存在并发），服务内部仅仅实例化一次引擎，难道我的用法不对
---- 回复的原邮件 ----
发件人Yutian ***@***.***>发送日期2024年04月25日 14:36 ***@***.***> ***@***.***>,
***@***.***>主题Re: [raoyutian/PaddleOCRSharp] 循环调用DetectText报错 (Issue #41)
4.1版本也是如此
那就不你知道你的问题所在了，我自己以及别人的服务都好好的。

**Comment by raoyutian** [comment]
> 我部署为 win 服务，然后多个客户端调用接口（存在并发），服务内部仅仅实例化一次引擎，难道我的用法不对 ---- 回复的原邮件 ---- 发件人Yutian ***@***.***>发送日期2024年04月25日 14:36 ***@***.***> ***@***.***>, ***@***.***>主题Re: [raoyutian/PaddleOCRSharp] 循环调用DetectText报错 (Issue #41) 4.1版本也是如此 那就不你知道你的问题所在了，我自己以及别人的服务都好好的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

并发服务，实例创建加锁，确保一个进程只创建一个实例

**Comment by igaobingbing** [comment]
代码是这样写的，时不时报这个错误
![image](https://github.com/raoyutian/PaddleOCRSharp/assets/74999292/a18ac734-b44f-49f8-9a73-c8687ca1d735)
