### ISSUE TITLE
Memory leak using mkldnn

### ISSUE THREAD

**Issue by Dr-Hex** [raoyutian/PaddleOCRSharp#49]
Hi,

I noticed constant memory growth when I recognize lot of images.
It's about +1GB RAM each 2000 images.

When I set:
```
oCRParameter.enable_mkldnn = false;
```
The leak is gone.

My config is:
```
OCRParameter oCRParameter = new OCRParameter();
oCRParameter.cpu_math_library_num_threads = 8;
oCRParameter.enable_mkldnn = true;
oCRParameter.cls = false;
oCRParameter.det = true;
oCRParameter.use_angle_cls = false;
oCRParameter.det_db_score_mode = true;
```
Model version 4.
PaddleOCRSharp version 4.4.0.1 (NuGet package).

Maybe it is related to mkldnn cache size.

Can you include in your API the config to change SetMkldnnCacheCapacity value?
Such as:
https://github.com/PaddlePaddle/Paddle/pull/25524/files
https://github.com/sdcb/PaddleSharp/pull/46/files

Thank you.

**Comment by Dr-Hex** [comment]
As addition: after several hours application RAM may grow up > 20 GB.
Of course, I checked a correct objects dispose in .NET code.
The only thing which helped is: enable_mkldnn = false;
My use case was ~ 20000 images of various sizes: from 450x40 until 3000x40. The final RAM was 10 GB.

As temporarily "walkaround" I tried to reload engine with FreeLibrary("PaddleOCR.dll") something like:
```
[DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
private static extern IntPtr LoadLibrary(string lpLibFileName);

[DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
private static extern IntPtr GetModuleHandle(string lpModuleName);

[DllImport("kernel32.dll", SetLastError = true)]
private static extern bool FreeLibrary(IntPtr hModule);

private static PaddleOCREngine? m_PaddleEngine;

// ...

private void CheckRAM()
{
	if (RAM > XXXXXXXX)
	{
		RebootEngine();
	}
}

[MethodImpl(MethodImplOptions.AggressiveOptimization)]
private void RebootEngine()
{
    WeakReference weakRef = new WeakReference(Globals.Paddle);
    if (m_PaddleEngine != null)
    {
        m_PaddleEngine.Dispose();
        GC.KeepAlive(m_PaddleEngine);
        m_PaddleEngine = null;
    }
    GC.Collect();
    GC.WaitForPendingFinalizers();
    if (weakRef.IsAlive)
    {
        return;
    }
    const int MAX_CountUnload = 100;
    int countUnload = 0;
    while (UnloadLibrary("PaddleOCR.dll") && countUnload++ < MAX_CountUnload) { };
	
    string libPath = Path.GetDirectoryName(System.AppDomain.CurrentDomain.BaseDirectory) + "\\" + "PaddleOCR.dll";
    var ptr = LoadLibrary(libPath);
    if (ptr != IntPtr.Zero)
    {
		// load engine
        PaddleOCREngine = new ...
    }
}

internal static bool UnloadLibrary(string libraryName)
{
    bool result = false;
    IntPtr hMod = GetModuleHandle(libraryName);
    if (hMod != IntPtr.Zero)
    {
        result = FreeLibrary(hMod);
    }
    Log.Info($"Unload result for {libraryName}: " + result);
    return result;
}
```
However, results are unstable.
For leak < 1 GB it reloads engine normally and flush the RAM. Application continues to work as usually.
For about > 2 GB, RAM flushed, then an attemt to create new PaddleOCRSharp instance failed with application crash.

**Comment by n0099** [comment]
https://github.com/raoyutian/PaddleOCRSharp/issues/50#issuecomment-2434914701

**Comment by Dr-Hex** [comment]
It was my fault.
After correct update (with the latest Paddle.Runtime.win_x64 package) no more leaks happen. Large dataset consume constantly not more than 1 GB RAM.
Before, I used dll dependencies from the previous PaddleOCRSharp version.
Sorry for bothering you.
