### ISSUE TITLE
32bit Version

### ISSUE THREAD

**Issue by mapo80** [raoyutian/PaddleOCRSharp#5]
Hi,

thanks for your work. Is it possibile to have 32bit version?
If not how can I build to make it compatible?

Thanks.

**Comment by raoyutian** [comment]
Sorry. it i has no  32bit version.This project is based on Baidu PaddlePaddle OCR，Baidu PaddlePaddle is only X64  cpu ON PC.
If you want to use it  in X86 cpu,you can build webapis or provide them as services to 32-bit programs.
Thanks.
