### ISSUE TITLE
Full source code

### ISSUE THREAD

**Issue by Dr-Hex** [raoyutian/PaddleOCRSharp#50]
Can you provide please the source code of modified C++ PaddleOCR library you used in this project?

I mentioned it is get removed from the repository for some reason.

So, at the moment I unsure how can I manually merge https://github.com/raoyutian/PaddleOCRSharp/pull/24 without having compatibility issues.

Thank you.

**Comment by raoyutian** [comment]
SetMkldnnCacheCapacity默认值是1,。

**Comment by raoyutian** [comment]
SetMkldnnCacheCapacity默认值是1。C++代码不再公开。

**Comment by Dr-Hex** [comment]
> SetMkldnnCacheCapacity默认值是1。

So, are you saying the latest NuGet 4.4.0.1 already uses prediction cache capacity == 1?

> C++代码不再公开。

But, may I ask you why?

I sincerely respect the work you did on simplification of the C++ base engine and this nice C# wrapper.
If that's something which should be now recognized as your own private fork, in that case may ask to buy it, or that's NDA as a part of commercial project?

**Comment by raoyutian** [comment]
> > SetMkldnnCacheCapacity默认值是1。
> 
> 那么，您是说最新的 NuGet 4.4.0.1 已经使用预测缓存容量 == 1 吗？
> 
> > C++ 代码不再公开。
> 
> 但是，请问你为什么？
> 
> 我由衷地尊重您在简化 C++ 基础引擎和这个漂亮的 C# 包装器方面所做的工作。如果这是现在应该被认定为你自己的私人分叉的东西，在这种情况下可以要求购买它，或者这是作为商业项目的一部分的 NDA？
商业化使用。CPU版本免费，GPU收费。C#的库PaddleOCRSharp公开代码。
C++代码，是不出售的。

**Comment by Dr-Hex** [comment]
Understand, thank you.
