### ISSUE TITLE
.Net 8.0 support

### ISSUE THREAD

**Issue by Dr-Hex** [raoyutian/PaddleOCRSharp#51]
There is misprint in readme:

```
本项目目前支持以下.NET框架：

net35;net40;net45;net451;net452;net46;net461;net462;net47;net471;net472;net48;net481;
netstandard2.0;netcoreapp3.1;
net5.0;net6.0;net7.0;net8.0
```

At the moment the project doesn't support net 8.0 from the source as is, and can't be easily modified to do so due to "Image" type compatibility on Windows platform.

**Comment by raoyutian** [comment]
本项目目前支持以下.NET框架：

net35;net40;net45;net451;net452;net46;net461;net462;net47;net471;net472;net48;net481;
netstandard2.0;netcoreapp3.1;
net5.0;net6.0;net7.0;net8.0
所有框架都测试过。是支持的。
Windows 平台上的“Image”也是支持的。

**Comment by Dr-Hex** [comment]
There is no net8.0 at:
https://github.com/raoyutian/PaddleOCRSharp/blob/5b47f1383285107e92c695557511cbfa4224561b/PaddleOCRSharp/PaddleOCRSharp.csproj#L18

And compiler throw "Image" type error when you try to add net8.0 or net8.0-windows7.0 as target.

Is this source code also deprecated/代码不再公开。?

**Comment by n0099** [comment]
https://github.com/raoyutian/PaddleOCRSharp/blob/5b47f1383285107e92c695557511cbfa4224561b/PaddleOCRSharp/EngineBase.cs#L125
https://stackoverflow.com/questions/43017826/using-system-drawing-imaging-imaging-does-not-exist-in-the-system-drawing

**Comment by raoyutian** [comment]
![1729776224258](https://github.com/user-attachments/assets/092c196d-4cbd-4533-8348-8bbbc6dba293)
最新代码在https://gitee.com/raoyutian/PaddleOCRSharp，
https://github.com/raoyutian/PaddleOCRSharp将不再提交代码。
![1729776357127](https://github.com/user-attachments/assets/4daab288-78b2-4805-940d-ab597e4b03fe)
![1729776456146](https://github.com/user-attachments/assets/f7d2041f-e993-4cd6-aac8-692618f15217)

**Comment by raoyutian** [comment]
![1729816824076](https://github.com/user-attachments/assets/f08d45ee-4e03-4b8f-81d7-a94cc714ebe6)
![1729816804032](https://github.com/user-attachments/assets/6366fcb4-d649-4722-a99b-296a0c613c57)
.net 8.0控制台示例项目。

**Comment by Dr-Hex** [comment]
I know it works on Windows. My question was related to the update.
For me, it gave a compilation error when trying to use multiple frameworks in csproj. When I use single net8.0 in csproj, then no issues.
Now I see the latest version is on getee and it is already updated with net 8.0.
Sorry for misunderstanding.

Good day to you and Good luck!
