### ISSUE TITLE
[regression] NuGet package missing important DLLs

### ISSUE THREAD

**Issue by Dr-Hex** [raoyutian/PaddleOCRSharp#52]
Unlike NuGet PaddleOCRSharp package version 4.3.0, the latest package version 4.4.0.1 missing most of important libraries.

Comparison of cache:

![изображение](https://github.com/user-attachments/assets/3d488697-3af2-418e-a2a9-e1d0d0674ffa)

The final project built in VS failed to work properly.

Steps to reproduce:

 - Open VS 2022
 - Create Net 8.0 project
 - Add NuGet package PaddleOCRSharp 4.4.0.1
 - Switch configuration as x64.
 - Build as release.

**Comment by raoyutian** [comment]
![1729776803828](https://github.com/user-attachments/assets/2021b845-7cd8-4a3a-a3cf-72fcd98e0e34)

**Comment by Dr-Hex** [comment]
I see. I need additional Paddle.Runtime.win_x64 NuGet package.
Thank you.
