### ISSUE TITLE
Nuget包的会一直提示libiomp5md.dll NUll

### ISSUE THREAD

**Issue by 1755812756** [raoyutian/PaddleOCRSharp#7]
左边Nuget包 右边是源码正常，Nuget包的会一直提示libiomp5md.dll NUll
![ee6ff6f8664b27dbc4572a82f4279581_145943_3d210075_5546353](https://user-images.githubusercontent.com/51776550/164171857-3d382c43-afc1-4766-b6cf-05b814ae4e02.png)

**Comment by raoyutian** [comment]
最新nuget包1.3.1已经修复。

**Comment by buzzlu** [comment]
2.0.2，在部署时又出现这个问题
