### ISSUE TITLE
是否楞以复制多份使用

### ISSUE THREAD

**Issue by raozhihao** [raoyutian/PaddleOCRSharp#9]
我在.net6中使用了该库，但因为不支持多线程，所以会出现资源争用的情况，导致出现各种异常
甩以不得不加锁，并设为了单例
但是这样会带来一个新的问题
我可能同时有十来个线程需要同时进行ocr识别
这如果其中有一些识别比较耗时且它们排在前面，就会导致后面的线程全部在等待中
会造成后面的线程的识别速度被降低

是否可以每一个线程我复制一份新的dll及其附加依赖项到另一个目录中使用呢？
就像我有1至10个线程，我new十个ocr对象且它们指向各自的目录库？

或者也可以多进程使用？

**Comment by raoyutian** [comment]
本项目不支持多线程。
至于其他方案，你可以去尝试

**Comment by raoyutian** [comment]
c++版本不支持多线程。
